services:
  db:
    image: postgres:17.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lcms
    ports:
      - "5432:5432"
    volumes:
      - postgres-17.6:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-7:/data
    command: redis-server --appendonly yes

  rails:
    image: lcms-core:3.4.7
    command: |
      bash -c "bundle install && rails server -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle-3.4.7:/usr/local/bundle
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=lcms
      - REDIS_URL=redis://redis:6379/0

  resque:
    image: lcms-core:3.4.7
    command: |
      bash -c "bundle install && bundle exec rake resque:work QUEUE=*"
    volumes:
      - .:/app
      - bundle-3.4.7:/usr/local/bundle
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=lcms
      - REDIS_URL=redis://redis:6379/0
      - TERM_CHILD=1
      - RESQUE_TERM_TIMEOUT=10

volumes:
  bundle-3.4.7:
  postgres-17.6:
  redis-7:
