services:
  db:
    image: postgres:17.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lcms
    ports:
      - "5432:5432"
    volumes:
      - postgres-17.6:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-7:/data
    command: redis-server --appendonly yes

  rails:
    image: lcms-core:dev
    command: |
      bash -c "bundle install && rm -rf tmp/pids && rails server -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker
      - .env.development

  resque:
    image: lcms-core:dev
    command: |
      bash -c "bundle install && env QUEUES=* COUNT=${RESQUE_COUNT:-1} bundle exec rake resque:workers"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker
      - .env.development
    environment:
      - TERM_CHILD=1
      - RESQUE_TERM_TIMEOUT=10

  css:
    image: lcms-core:dev
    command: |
      bash -c "yarn install && yarn watch:css"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app

  js:
    image: lcms-core:dev
    command: |
      bash -c "yarn install && yarn build"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app

  test:
    image: lcms-core:dev
    env_file:
      - .env.docker
    environment:
      - DATABASE_NAME=lcms_test
      - RAILS_ENV=test
    command: bundle exec rspec
    volumes:
      - .:/app
      - bundle:/usr/local/bundle

volumes:
  bundle:
  postgres-17.6:
  redis-7:
